name: The Heritage Renewal Company
favicon: null
layout_spectrum: 0.2592469819355756
typography_spectrum: 0.4185290038585663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#8b9094'
    - '#2b2d20'
    - '#555440'
  brandStrength: 0.625
  lightness: 0.7105217957869172
  saturation: 0.33591956924647093
  rhythmicContrast: 0.22640670998953283
purpose: []
