name: The Heritage Renewal Company
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4185290038585663
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b7a798'
    - '#363227'
    - '#6a5840'
    - '#060000'
    - '#eae4e0'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.33591956924647093
  rhythmicContrast: 0
purpose: []
